name: Run Robot Framework Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 1 1 *"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create folder for reports
        run: mkdir reports

      - name: Run Robot Framework Tests
        run: |
          docker run \
            -v ${PWD}/reports:/opt/robotframework/reports:Z \
            -v ${PWD}/android/features:/opt/robotframework/tests:Z \
            -v ${PWD}/android/utils:/opt/robotframework/utils:Z \
            --user $(id -u):$(id -g) \
            ppodgorsek/robot-framework:latest

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
